debug: false

server:
  error:
    path: /error/404.html
    whitelabel:
      enabled: false

logging:
  level:
    sql: debug
    org:
      hibernate:
        persister:
          entity: ERROR

#jasypt:
#  encryptor:
#    password: corebase
#    bean: jasyptStringEncryptor
#    property:
#      prefix: ENC(
#      suffix: )
    
spring:
#  profiles:
#    active: local
  config:
    import:
    - environment.properties

#---
#spring:
#  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
#---
#spring:
#  profiles: mysql
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
#      username: jojoldu
#      password: jojoldu1
#      driver-class-name: com.mysql.jdbc.Driver
    
    
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation:true
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

  batch:
    jdbc:
      initialize-schema: never
      table-prefix: BATCH_
    job:
      enabled: false
      
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    cache: false

  mail :
    host : smtp.gmail.com
    port : 587
    username : 'your email'
    password : 'your password'
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true
    
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    use-root-path: true