alter table if exists cm_cd_dtl    drop    foreign key if exists FK_cm_cd_dtl;
alter table if exists cm_menu_dtl    drop    foreign key if exists FK_cm_menu_dtl;
alter table if exists cm_menu_dtl_role_map    drop    foreign key if exists FK_cm_menu_dtl_role_map1;
alter table if exists cm_menu_dtl_role_map    drop    foreign key if exists FK_cm_menu_dtl_role_map2;
alter table if exists cm_noti_user_map    drop    foreign key if exists FK_cm_noti_user_map1;   
alter table if exists cm_noti_user_map    drop    foreign key if exists FK_cm_noti_user_map2;   
alter table if exists cm_role_menu_map    drop    foreign key if exists FK_cm_role_menu_map1;   
alter table if exists cm_role_menu_map    drop    foreign key if exists FK_cm_role_menu_map2;
alter table if exists cm_user_alow_ip    drop    foreign key if exists FK_cm_user_alow_ip;
alter table if exists cm_user_pwd    drop    foreign key if exists FK_cm_user_pwd;
alter table if exists cm_user_role_map    drop    foreign key if exists FK_cm_user_role_map1;
alter table if exists cm_user_role_map    drop    foreign key if exists FK_cm_user_role_map2;
alter table if exists td_checker_map    drop    foreign key if exists FK_td_checker_map;
alter table if exists td_quiz_work_use    drop    foreign key if exists FK_td_quiz_work_use1;
alter table if exists td_quiz_work_use    drop    foreign key if exists FK_td_quiz_work_use2;
alter table if exists td_work    drop    foreign key if exists FK_td_work1;
alter table if exists td_work    drop    foreign key if exists FK_td_work2;
alter table if exists td_worker_map    drop    foreign key if exists FK_td_worker_map;
     
       
drop table if exists cm_cd_dtl;
drop table if exists cm_cd_grp;
drop table if exists cm_menu;
drop table if exists cm_menu_dtl;
drop table if exists cm_menu_dtl_role_map;
drop table if exists cm_noti;
drop table if exists cm_noti_user_map;
drop table if exists cm_role;
drop table if exists cm_role_chg_log;
drop table if exists cm_role_menu_map;
drop table if exists cm_user;
drop table if exists cm_user_alow_ip;
drop table if exists cm_user_pwd;
drop table if exists cm_user_relat;
drop table if exists cm_user_role_map;
drop table if exists td_checker_map;
drop table if exists td_quiz;
drop table if exists td_quiz_work_use;
drop table if exists td_setle;
drop table if exists td_todo;
drop table if exists td_work;
drop table if exists td_worker_map;
drop table if exists td_point;