package kr.co.basedevice.corebase.domain.code;

public enum WriteMakrCd {
	LOGIN_SUCCESS_FORM, 
	LOGIN_FAIL_FORM, 
	LOGIN_SUCCESS_AJAX, 
	LOGIN_FAIL_AJAX, 
	ACCESS_DENIED,
	LOGOUT_SUCCESS,
	INTERNAL_SERVER_ERROR,
	OTHER_ERRROR
}
